name: release and deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  deploy-pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

  pypi-index:
    needs: deploy-pypi
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install from PyPI
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          PKGNAME=$(python setup.py --name)
          VERSION=$(python setup.py --version)
          while true; do python -m pip install $PKGNAME==$VERSION && break || sleep 5; done

  deploy-docker:
    needs: pypi-index
    runs-on: ubuntu-latest
    steps:
      - name: extract version from tag
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e "s/^refs\/tags\///")
          VERSION=${TAG_NAME#v}
          echo "Tag Name: $TAG_NAME"
          echo "Version: $VERSION"
          echo "PKG_VERSION=$VERSION" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/akfamily/aktools
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile-Release
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          build-args: |
            VERSION=${{ env.PKG_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
